version: '3'

services:
  # PHP Service
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: always
    volumes:
      - .:/var/www/html
    environment:
      - PHP_FPM_LARAVEL=true
    networks:
      - laravel-net
    depends_on:
      - db
      - redis

  # Nginx Service
  web:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-net

  # MySQL Service
  db:
    image: woahbase/alpine-mysql
    container_name: laravel-mysql
    restart: always
    environment:
      MYSQL_ROOT_PWD: ${DB_ROOT_PASSWORD}
      MYSQL_USER_DB: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_USER_PWD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravel-net
    ports:
      - "3306:3306"

  # Redis Service
  redis:
    image: redis:alpine
    container_name: laravel-redis
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./docker/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/data:/data
    networks:
      - laravel-net
    ports:
      - "6379:6379"

  composer:
    image: composer
    container_name: laravel-composer
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge

volumes:
  mysql-data:
